version: "3.7"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-gces:/var/lib/postgresql/data

  backend:
    image: python:3-alpine
    ports:
      - 8000:8000
    command:
    - /bin/sh
    - -c
    - |
      apk add --no-cache postgresql-libs
      apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev
      cd library_back
      python3 -m venv env
      . env/bin/activate
      python3 -m pip install -r requirements.txt
      python3 manage.py makemigrations
      python3 manage.py migrate
      python3 manage.py runserver 0.0.0.0:8000
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres-gces:
