version: "3.7"
services:
  builddb:
    build: ../postgres

  buildbe:
    build: ../library_back
  buildfe:
    build: ../library_front
  test:
    image: node:12-alpine
    command: sh -c "npm install && npm test -- --watchAll=false"
    working_dir: /app/library_front
    volumes:
      - ../:/app/

  lint:
    image: node:12-alpine
    command: sh -c "npm install && npm run lint"
    working_dir: /app/library_front
    volumes:
      - ../:/app/


volumes:
  postgres-gces:
