name: Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ci/docker-compose.yml

    steps:
    - name: Check
      uses: actions/checkout@v2

    - name: Run lint
      run: docker-compose up lint
