name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ci/docker-compose.yml

    steps:
    - name: Check
      uses: actions/checkout@v2

    - name: Run tests
      run: docker-compose up test
